E-Sports app/UI/Models/MyTeamModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Middletier;

namespace UI.Models
{
    public class MyTeamModel
    {
        #region Fields

       
        public Team team = new Team();
        public List<Team> Myteams = new List<Team>();
        public List<Team> AllTeams = new List<Team>();
        public List<Team> OtherTeams = new List<Team>();

        #endregion

        #region Methods

        public void LoadAllTeams()
        {
            foreach (Team team in team.GetAllTeams())
            {
                AllTeams.Add(team);
            }
        }

        public void LoadMyTeams(User loggedinuser)
        {
            foreach(Team team in team.GetMyTeams(loggedinuser))
            {
                Myteams.Add(team);
            }
        }

        public void FillOtherTeams()
        {
            foreach (Team team in AllTeams)
            {
                if (!Myteams.Contains(team))
                {
                    OtherTeams.Add(team);
                }
            }
        }

        #endregion
    }
}

E-Sports app/UI/Models/SpecificTournamentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Middletier;

namespace UI.Models
{
    public class SpecificTournamentModel
    {
        public Tournament tournament = new Tournament();
    }
}

E-Sports app/UI/Models/StartPaginaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Middletier;

namespace UI.Models
{
    public class StartPaginaModel
    {
        #region Fields

        public User LoggedInUser = new User("User1", Account_Type.Player, "Leroy", "Van de Ven", "84745834", "Vi0llet", "leroylyon@hotmail.com");
        private Tournament tournament = new Tournament();
        public List<Tournament> tournaments = new List<Tournament>();

        #endregion

        #region Methods

        public void LoadAllTournaments()
        {
            foreach (Tournament tournament in tournament.GetallTournaments())
            {
                tournaments.Add(tournament);
            }
        }

        #endregion
    }
}

E-Sports app/UI/Models/TournamentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Middletier;

namespace UI.Models
{
    public class TournamentModel
    {
        #region Fields

        private SpecificTournamentModel tournamentmodel = new SpecificTournamentModel();
        private Tournament Tournament = new Tournament();
        public List<Team> participants = new List<Team>();
        public List<Tournament> MyTournaments = new List<Tournament>();
        public List<Tournament> AllTournaments = new List<Tournament>();
        public List<Rule> Rules = new List<Rule>();
        public List<Price> Prices = new List<Price>();
        public List<Match> Matches = new List<Match>();

        #endregion

        #region Methods

        public void LoadParticipants()
        {
            foreach(Team team in Tournament.Participants)
            {
                participants.Add(team);
            }
        }

        public void LoadAllTournaments()
        {
            foreach (Tournament tournament in Tournament.GetallTournaments())
            {
                AllTournaments.Add(tournament);
            }
        }

        public void LoadMyTournaments(User loggedinuser)
        {
            foreach (Tournament tournament in Tournament.GetMyTournaments(loggedinuser))
            {
                MyTournaments.Add(tournament);
            }
        }
       
        public void GetMatches()
        {
            foreach (Match match in Tournament.Matches)
            {
                Matches.Add(match);
            }
        }

        public void GetPrices()
        {
            foreach (Price price in Tournament.Prizes)
            {
                Prices.Add(price);
            }
        }

        public void GetRules()
        {
            foreach (Rule rule in Tournament.Rules)
            {
                Rules.Add(rule);
            }
        }

        public Tournament GetSpecificTournament(int ID)
        {
            foreach(Tournament tournament in AllTournaments)
            {
                if(tournament.ID == ID)
                {
                    tournamentmodel.tournament = tournament;
                }
            }
            return tournamentmodel.tournament;
        }

        #endregion
    }
}

E-Sports app/UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

E-Sports app/UI/Controllers/MyTeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;
using Middletier;

namespace UI.Controllers
{
    public class MyTeamController : Controller
    {

        User LoggedInUser = new User("User1", Account_Type.Player, "Leroy", "Van de Ven", "84745834", "Vi0llet", "Leroylyon@hotmail.com");

        // GET: MyTeam
        public ActionResult Index()
        {
            MyTeamModel model = new MyTeamModel();
            model.LoadAllTeams();
            model.LoadMyTeams(LoggedInUser);
            model.FillOtherTeams();
            return View(model);
        }

        public RedirectToRouteResult AddTeam(Team team)
        {
            LoggedInUser.AddTeam(team);
            team.AddMember(LoggedInUser);
            return RedirectToAction("Index", "MyTeam");
        }
    }
}

E-Sports app/UI/Controllers/ProfielController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class ProfielController : Controller
    {
        // GET: Profiel
        public ActionResult Index()
        {
            return View();
        }
    }
}

E-Sports app/UI/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;
using Middletier;

namespace UI.Controllers
{
    public class TournamentController : Controller
    {
        SpecificTournamentModel tournamentmodel = new SpecificTournamentModel();
        TournamentModel model = new TournamentModel();
        User LoggedInUser = new User("User1", Account_Type.Player, "Leroy", "Van de Ven", "84745834", "Vi0llet", "Leroylyon@hotmail.com");

        // GET: Tournament
        public ActionResult Index()
        {
            model.LoadAllTournaments();
            model.LoadMyTournaments(LoggedInUser);
            model.LoadParticipants();
            model.GetPrices();
            model.GetRules();
            return View(model);
        }
        
        public ActionResult Tournament(int id)
        {
            model.GetSpecificTournament(id);
            return View(tournamentmodel);
        }
    }
}

E-Sports app/UI/Views/Home/Index.cshtml
@using Middletier;
@model UI.Models.StartPaginaModel
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Logged in with: @Model.LoggedInUser.SirName "@Model.LoggedInUser.Username" @Model.LoggedInUser.Lastname</h2>
<hr />
<br />
<text >Welcome to the FindYourGame. <br />
    <br />
      On this site you will be able to Participate in tournaments and win dependent on how well you play.<br />
      <br />
    <br />
      If you are ready, lets continue</text>
<br/>
<br/>
@Html.ActionLink("My Teams", "Index", "MyTeam")

E-Sports app/UI/Views/MyTeam/Index.cshtml
@using Middletier;
@model UI.Models.MyTeamModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Teams</h2>
<hr />

<div>here you will find a overview of the team that you joined:</div>
<br />
<div><h3>My teams: </h3></div>
@if(Model.Myteams.Count == 0)
{
    <br />
    <div>U maakt nog geen deel uit van een team</div>
}
@foreach (Team team in Model.Myteams)
{
    <br />
    <div>@team.TeamName, @team.ShortHandle</div>
}
<br /> 
<br />

<div><h3>All teams: </h3></div>
@foreach (Team team in Model.OtherTeams)
{
    <br />
    <div>@team.TeamName, @team.ShortHandle  @Html.ActionLink("Join", "AddTeam", "MyTeam", Model.team.TeamName)</div>
}

E-Sports app/UI/Views/Profiel/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deze pagina wordt niet door Leroy gemaakt.</h2>

E-Sports app/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FindYourGame", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tournaments", "Index", "Tournament")</li>
                    <li>@Html.ActionLink("My Teams", "Index", "MyTeam")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profiel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

E-Sports app/UI/Views/Tournament/Index.cshtml
@using Middletier;
@model UI.Models.TournamentModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tournaments</h2>
<hr />

<div>here you will find a overview of the tournaments:</div>
<br />
<div><h3>My tournaments: </h3></div>
@if (Model.MyTournaments.Count == 0)
{
    <br />
    <div>you didnt sign your team up for any tournaments yet</div>
}
@foreach (Tournament tournament in Model.MyTournaments)
{
    <br />
    <div>@Html.ActionLink(""+@tournament.Name+"", "Tournament", "Tournament", new { id = tournament.ID }, null) <br /> Start: @tournament.StartDate</div>
}
<br />
<br />

<div><h3>All tournaments: </h3></div>
@foreach (Tournament tournament in Model.AllTournaments)
{
    <br />
    <div>@tournament.Name<br /> start: @tournament.StartDate</div>
}

E-Sports app/UI/Views/Tournament/Tournament.cshtml
@using Middletier;
@model UI.Models.SpecificTournamentModel
@{
    ViewBag.Title = "Tournament";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.tournament.Name</h2>